[tool.poetry]
name = "algoworld-contracts"
version = "0.1.0"
description = "AlgoWorld Smart Contracts and Signature"
authors = ["MillionAlgosFather <info@algoworld.io>"]

[tool.poetry.dependencies]
python = "^3.8"
pyteal = "0.10.1"
py-algorand-sdk = "1.10.0"
PyYAML = ">=3.2.1,<4.0.0"

[tool.poetry.dev-dependencies]
black = {version = "^21.9b0", allow-prereleases = true}
pytest = "^7.0.0"
pytest-depends = "^1.0.1"
pytest-docker-compose = "^3.2.1"
requests = "^2.27.1"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
